export const SAVE_FUEL_REQUEST_DATA = 'SAVE_FUEL_REQUEST_DATA';
export const ADD_SUCCESS_FUEL_REQUEST_DATA = 'ADD_SUCCESS_FUEL_REQUEST_DATA';
export const ADD_FAILED_FUEL_REQUEST_DATA = 'ADD_FAILED_FUEL_REQUEST_DATA';
export const GET_ALL_FUEL_REQUEST_DATA = 'GET_ALL_FUEL_REQUEST_DATA';
export const SUCCESS_GET_ALL_FUEL_REQUEST_DATA = 'SUCCESS_GET_ALL_FUEL_REQUEST_DATA';
export const FAILED_GET_ALL_FUEL_REQUEST_DATA = 'FAILED_GET_ALL_FUEL_REQUEST_DATA';
export const GET_FUEL_REQUEST_DETAILS_BY_CODE = 'GET_FUEL_REQUEST_DETAILS_BY_CODE';
export const SUCCESS_GET_FUEL_REQUEST_DETAILS_BY_CODE = 'SUCCESS_GET_FUEL_REQUEST_DETAILS_BY_CODE';
export const FAILED_GET_FUEL_REQUEST_DETAILS_BY_CODE = 'FAILED_GET_FUEL_REQUEST_DETAILS_BY_CODE';
export const UPDATE_FUEL_REQUEST_DATA = 'UPDATE_FUEL_REQUEST_DATA';
export const UPDATE_SUCCESS_FUEL_REQUEST_DATA = 'UPDATE_SUCCESS_FUEL_REQUEST_DATA';
export const UPDATE_FAILED_FUEL_REQUEST_DATA = 'UPDATE_FAILED_FUEL_REQUEST_DATA';
export const CHECK_FUEL_REQUEST_NUMBER_DUPLICATE = 'CHECK_FUEL_REQUEST_NUMBER_DUPLICATE';
export const FUEL_REQUEST_NUMBER_DUPLICATE = 'FUEL_REQUEST_NUMBER_DUPLICATE';
export const CHECK_CHASSIS_NUMBER_DUPLICATE = 'CHECK_CHASSIS_NUMBER_DUPLICATE';
export const CHASSIS_NUMBER_DUPLICATE = 'CHASSIS_NUMBER_DUPLICATE';
export const GET_FUEL_REQUEST_LAST_MODIFIED_DATE_TIME = ' GET_FUEL_REQUEST_LAST_MODIFIED_DATE_TIME';
export const SUCCESS_GET_FUEL_REQUEST_LAST_MODIFIED_DATE_TIME = 'SUCCESS_GET_FUEL_REQUEST_LAST_MODIFIED_DATE_TIME';
export const FAILED_GET_FUEL_REQUEST_LAST_MODIFIED_DATE_TIME = 'FAILED_GET_FUEL_REQUEST_LAST_MODIFIED_DATE_TIME';
export const FAILED_ALL_CLUSTER_TYPE_DATA = 'FAILED_ALL_CLUSTER_TYPE_DATA';

export const GET_ALL_ACTIVE_FUEL_REQUEST_DATA = 'GET_ALL_ACTIVE_FUEL_REQUEST_DATA';
export const SUCCESS_GET_ALL_ACTIVE_FUEL_REQUEST_DATA = 'SUCCESS_GET_ALL_ACTIVE_FUEL_REQUEST_DATA';
export const FAILED_GET_ALL_ACTIVE_FUEL_REQUEST_DATA = 'FAILED_GET_ALL_ACTIVE_FUEL_REQUEST_DATA';

export const GET_QUOTA_BY_VEHICLE_NUMBER = 'GET_QUOTA_BY_VEHICLE_NUMBER ';
export const SUCCESS_GET_QUOTA_BY_VEHICLE_NUMBER = 'SUCCESS_GET_QUOTA_BY_VEHICLE_NUMBER ';
export const FAILED_GET_QUOTA_BY_VEHICLE_NUMBER = 'FAILED_GET_QUOTA_BY_VEHICLE_NUMBER ';

export const GET_ALL_FUEL_REQUEST_DATA_BY_USER = 'GET_ALL_FUEL_REQUEST_DATA_BY_USER';
export const SUCCESS_GET_ALL_FUEL_REQUEST_DATA_BY_USER = 'SUCCESS_GET_ALL_FUEL_REQUEST_DATA_BY_USER';
export const FAILED_GET_ALL_FUEL_REQUEST_DATA_BY_USER = 'FAILED_GET_ALL_FUEL_REQUEST_DATA_BY_USER';

export const GET_WEEK_END_DATE = 'GET_WEEK_END_DATE';
export const SUCCESS_GET_WEEK_END_DATE = 'SUCCESS_GET_WEEK_END_DATE';

export const DELETE_FUEL_REQUEST_DETAILS_BY_ID = 'DELETE_FUEL_REQUEST_DETAILS_BY_ID';
export const SUCCESS_DELETE_FUEL_REQUEST_DETAILS_BY_ID = 'SUCCESS_DELETE_FUEL_REQUEST_DETAILS_BY_ID';
export const FAILED_DELETE_FUEL_REQUEST_DETAILS_BY_ID = 'FAILED_DELETE_FUEL_REQUEST_DETAILS_BY_ID';

export const ACCEPT_FUEL_REQUEST_DETAILS_BY_ID = 'ACCEPT_FUEL_REQUEST_DETAILS_BY_ID';
export const SUCCESS_ACCEPT_FUEL_REQUEST_DETAILS_BY_ID = 'SUCCESS_ACCEPT_FUEL_REQUEST_DETAILS_BY_ID';
export const FAILED_ACCEPT_FUEL_REQUEST_DETAILS_BY_ID = 'FAILED_ACCEPT_FUEL_REQUEST_DETAILS_BY_ID';

export const REJECT_FUEL_REQUEST_DETAILS_BY_ID = 'REJECT_FUEL_REQUEST_DETAILS_BY_ID';
export const SUCCESS_REJECT_FUEL_REQUEST_DETAILS_BY_ID = 'SUCCESS_REJECT_FUEL_REQUEST_DETAILS_BY_ID';
export const FAILED_REJECT_FUEL_REQUEST_DETAILS_BY_ID = 'FAILED_REJECT_FUEL_REQUEST_DETAILS_BY_ID';

// fuel request by filling station

export const SAVE_FUEL_REQUEST_BY_FILLING_STATION_DATA = 'SAVE_FUEL_REQUEST_BY_FILLING_STATION_DATA';
export const ADD_SUCCESS_FUEL_REQUEST_BY_FILLING_STATION_DATA = 'ADD_SUCCESS_FUEL_REQUEST_BY_FILLING_STATION_DATA';
export const ADD_FAILED_FUEL_REQUEST_BY_FILLING_STATION_DATA = 'ADD_FAILED_FUEL_REQUEST_BY_FILLING_STATION_DATA';
export const GET_ALL_FUEL_REQUEST_BY_FILLING_STATION_DATA = 'GET_ALL_FUEL_REQUEST_BY_FILLING_STATION_DATA';
export const SUCCESS_GET_ALL_FUEL_REQUEST_BY_FILLING_STATION_DATA = 'SUCCESS_GET_ALL_FUEL_REQUEST_BY_FILLING_STATION_DATA';
export const FAILED_GET_ALL_FUEL_REQUEST_BY_FILLING_STATION_DATA = 'FAILED_GET_ALL_FUEL_REQUEST_BY_FILLING_STATION_DATA';
// export const GET_FUEL_REQUEST_DETAILS_BY_CODE = 'GET_FUEL_REQUEST_DETAILS_BY_CODE';
// export const SUCCESS_GET_FUEL_REQUEST_DETAILS_BY_CODE = 'SUCCESS_GET_FUEL_REQUEST_DETAILS_BY_CODE';
// export const FAILED_GET_FUEL_REQUEST_DETAILS_BY_CODE = 'FAILED_GET_FUEL_REQUEST_DETAILS_BY_CODE';
// export const UPDATE_FUEL_REQUEST_DATA = 'UPDATE_FUEL_REQUEST_DATA';
// export const UPDATE_SUCCESS_FUEL_REQUEST_DATA = 'UPDATE_SUCCESS_FUEL_REQUEST_DATA';
// export const UPDATE_FAILED_FUEL_REQUEST_DATA = 'UPDATE_FAILED_FUEL_REQUEST_DATA';

export const GET_ALL_FUEL_REQUEST_BY_ALL_FILLING_STATION_DATA = 'GET_ALL_FUEL_REQUEST_BY_ALL_FILLING_STATION_DATA';
export const SUCCESS_GET_ALL_FUEL_REQUEST_BY_ALL_FILLING_STATION_DATA = 'SUCCESS_GET_ALL_FUEL_REQUEST_BY_ALL_FILLING_STATION_DATA';
export const FAILED_GET_ALL_FUEL_REQUEST_BY_ALL_FILLING_STATION_DATA = 'FAILED_GET_ALL_FUEL_REQUEST_BY_ALL_FILLING_STATION_DATA';
